### ISSUE TITLE
PHGServerCon, unable to make graph

### ISSUE THREAD

**Issue by tysthomas** [maize-genetics/rPHG2#9]
I have used rPHGv1 with server connection to maizegdb and was able to set a method such as `G2F_2014-2023_PATHS`. I have been looking for documentation here on how to use a server connection and I have been unsuccessful. I am unable to make a graph while using a server connection. Can rPHG2 server connection be used similar to rPHGv1?

**Comment by btmonier** [comment]
Posting this here for posterity, but in (`rPHG`)[https://rphg.maizegenetics.net/], you can cross-ref the sample DB IDs (e.g. the elements of the hap ID matrix) (`sampleDbId`) with the call set names (`callSetNames`) using the `data.frame` object processed from the following code:

``` r
library(rPHG)

srvCon <- PHGServerCon("phg.maizegdb.org")

sampleDbIds <- srvCon |>
    brapiURL() |>
    paste0("/callsets") |> 
    httr::GET() |> 
    httr::content("text", encoding = "UTF-8") |> 
    jsonlite::fromJSON() |>
    _$result$data |>
    tibble::as_tibble()
```

Due to changes in how we distribute information in PHGv2, this approach will change subsequently in `rPHG2`.
